# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wine_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=30)),
                ('wine_year', models.CharField(max_length=4)),
                ('wine_sweetness', models.CharField(choices=[('Slodkie', 'Slodkie'), ('Polslodkie', 'Polslodkie'), ('Polwytrawne', 'Polwytrawne'), ('Wytrawne', 'Wytrawne')], default='Wytrawne', max_length=10)),
                ('wine_color', models.CharField(choices=[('Biale', 'Biale'), ('Czerwone', 'Czerwone')], default='Czerwone', max_length=8)),
            ],
        ),
    ]
