# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_wine_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dokument',
        ),
        migrations.DeleteModel(
            name='wine_list',
        ),
    ]
