# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=4)),
                ('city', models.CharField(max_length=50)),
                ('zip_number', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DocList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(choices=[('WZ', 'WZ'), ('PZ', 'PZ'), ('RW', 'RW'), ('PW', 'PW')], default='WZ', max_length=2)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itswine', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=15)),
                ('dryness', models.CharField(max_length=20)),
            ],
        ),
    ]
