# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_doclist_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='DocList',
            new_name='Doc',
        ),
        migrations.RenameModel(
            old_name='ProductList',
            new_name='Product',
        ),
    ]
