# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import doc.models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_auto_20160801_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.Client'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='number',
            field=models.IntegerField(default=doc.models.getNumber),
        ),
    ]
