# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_auto_20160802_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('value', models.FloatField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Doc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Product')),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('value', models.FloatField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Doc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Product')),
            ],
        ),
    ]
