# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_expenditure_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='number',
            new_name='docum',
        ),
    ]
