# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_auto_20160816_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='number',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='product',
        ),
        migrations.DeleteModel(
            name='expenditure',
        ),
    ]
