# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wzki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('WZ', 'WZ'), ('PZ', 'PZ'), ('RW', 'RW'), ('PW', 'PW')], default='WZ', max_length=2)),
                ('numeracja', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WineList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=50)),
                ('wine_year', models.CharField(max_length=4)),
                ('wine_color', models.CharField(choices=[('Czerwone', 'Czerwone'), ('Biale', 'Biale'), ('Rozowe', 'Rozowe')], default='Czerwone', max_length=8)),
                ('wine_taste', models.CharField(choices=[('Wytrawne', 'Wytrawne'), ('Polwytrawne', 'Polwytrawne'), ('Slodkie', 'Slodkie'), ('Polslodkie', 'Polslodkie')], default='Wytrawne', max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Doc_list',
        ),
    ]
